update to use ChatOllama class

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -64,7 +64,17 @@ services:
 
         echo "Pulling initium/law_model..."
         if ! ollama pull initium/law_model; then
-          echo "❌ ERROR: Failed to pull Llama3 model. Exiting."
+          echo "❌ ERROR: Failed to pull initium/law_mode model. Exiting."
+          exit 1  # 🔥 Fail the container if model pull fails
+        fi
+        echo "Pulling llama3.2..."
+        if ! ollama pull llama3.2; then
+          echo "❌ ERROR: Failed to pull llama3.2 model. Exiting."
+          exit 1  # 🔥 Fail the container if model pull fails
+        fi
+        echo "Pulling llama3.1..."
+        if ! ollama pull llama3.1; then
+          echo "❌ ERROR: Failed to pull llama3.1 model. Exiting."
           exit 1  # 🔥 Fail the container if model pull fails
         fi
         echo "Model downloaded. Keeping Ollama running..."
